variables:
  NODE_VERSION: 18.16.1

stages:
  - linting
  - formatting
  - deploy-production

Linting Check:
  stage: linting
  image: node:$NODE_VERSION
  before_script:
    - yarn
  script:
    - yarn lint
  environment: linting
  only:
    - main

formatting-check:
  stage: formatting
  image: node:$NODE_VERSION
  before_script:
    - yarn
  script:
    - yarn prettier
  environment: formatting
  only:
    - main

deploy-to-production:
  stage: deploy-production
  image: node:$NODE_VERSION
  before_script:
    - yarn
  script:
    - curl -s "https://api.render.com/deploy/srv-$DEPLOY_HOOK_01?key=$DEPLOY_HOOK_02" -o file.txt >/dev/null 2>&1
  environment:
    name: production
    url: https://dashboard.render.com/web/srv-$DEPLOY_HOOK_01
  only:
    - main
