stages:
  - linting
  - formatting
  - deploy-production

linting-check:
  stage: linting
  image: node:latest
  before_script:
    - npm install -g yarn
    - yarn
  script:
    - echo "Linting Check"
    - yarn lint
  environment: linting
  only:
    - main

formatting-check:
  stage: formatting
  image: ubuntu:latest
  before_script:
    - apt-get update -yq
    - apt-get install -yq nodejs
    - apt-get install -yq npm
  script:
    - npm install -g yarn
    - yarn
    - echo "Formatting Check"
    - yarn prettier
  environment: formatting
  only:
    - main

deploy-to-production:
  stage: deploy-production
  image: ubuntu:latest
  before_script:
    - apt-get update -yq
    - apt-get install -yq nodejs
    - apt-get install -yq npm
  script:
    - npm install -g yarn
    - yarn
    - echo "Deploy to production server"
    - curl -s "https://api.render.com/deploy/srv-$DEPLOY_HOOK_01?key=$DEPLOY_HOOK_02" -o file.txt >/dev/null 2>&1
  environment:
    name: production
    url: https://dashboard.render.com/web/srv-$DEPLOY_HOOK_01
  only:
    - main
